### ISSUE TITLE
Bypass to prop push

### ISSUE THREAD

**Issue by dmephi** [LuaTenshi/GLua#10]
If you spawn 2 props really fast the second one will be able to prop push players.

**Comment by NanoAi** [comment]
Even with ghosting on spawn? Thanks for letting me know also try using the
latest github release at https://github.com/LuaTenshi/APAnti and see if the
issue still happens.

**Comment by dmephi** [comment]
I got this running in sandbox gamemode 
"[APA] CPPI not found, APAnti will be heavily limited.

[ERROR] CPPI not found, APAnti will be heavily limited.
1. error - [C]:-1
   1. unknown - workshop/lua/sv_apanti.lua:91
   2. include - [C]:-1
      1. v - workshop/lua/autorun/server/apa_init.lua:99
      2. unknown - lua/includes/modules/hook.lua:84
         "

But darkrp you can still prop push even if ghost on spawn is turned on or off.

Sorry for the late reply my gmod decided to break because TF2 was not updated. Thanks for the quick reply :)

**Comment by NanoAi** [comment]
Try using the latest github release at https://github.com/LuaTenshi/APAnti and see if the issue still happens.

Also the error you pasted is an error that is inserted into the code by me, its just letting you know that you don't have [CPPI](https://facepunch.com/showthread.php?t=488410) so stuff like ghosting which needs CPPI won't work... CPPI ussually comes with prop protection scripts it is included in [FPP](https://github.com/FPtje/Falcos-Prop-protection) and FPP is also a part of DarkRP.

As for the ghosting issue you are having it's because the FPP ghosting is conflicting with the APAnti ghosting this should be fixed in the [latest version](https://github.com/LuaTenshi/APAnti).

**Comment by dmephi** [comment]
It is still the same problem. What settings did you have fpp on? (mine are on default) The only way I can fix it is to take off antispam.
